name: ilumina
description: "Bring fun and exotic textures to your images and photos."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.3
  flutter:
    sdk: flutter
  rive: ^0.14.0-dev.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
